### ISSUE TITLE
ConcurrentModificationException / IndexOutOfBoundsException

### ISSUE THREAD

**Issue by PencilVoid** [Goby56/wakes#1]
[Crash report](https://mclo.gs/CcPMkmL)
Minecraft 1.20.1
Quilt Loader 0.19.2

Initially the mod worked fine but after a few minutes it began to crash whenever a wake was visible. Since it first crashed while I was in a boat it would crash after loading the world until I removed the mod.

**Comment by Goby56** [comment]
I think I've found what was causing the issue but I cant be too sure as I've not been able to reproduce the crash myself.

Please test the [latest release](https://github.com/Goby56/wakes/releases/tag/debug) and let me know if the issue still persists.

**Comment by PencilVoid** [comment]
With the latest release it seems the error still occurs but the game crashes after a few minutes rather than immediately upon loading the world.
[Crash report](https://mclo.gs/2hc9V36)

**Comment by Steveplays28** [comment]
Same issue, here's my [log file](https://mclo.gs/132auDi).

**Comment by Goby56** [comment]
I'm lost for ideas to fix this but I'll recommend you a mod that can potentially fix it. [Voyager](https://github.com/modmuss50/Voyager/releases/tag/1.0.0) is a mod made by developer at fabric that fixes this very error. I don't know if it will be of any help as it is my own mod which casues the error but please give it a shot and notify me if you still get the crashes.

**Comment by Steveplays28** [comment]
I can try loading the newest version of Wakes and Voyager on my server sometime

**Comment by uricot** [comment]
same issue for me

**Comment by Lafolie** [comment]
Hi, I have also encountered this issue.
```py
[17:31:02] [Render thread/ERROR]: Unreported exception thrown!
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
	at com.goby56.wakes.utils.WakeHandler.tick(WakeHandler.java:57) ~[wakes-0.1.7.jar:?]
	at com.goby56.wakes.event.WakeTicker.onEndTick(WakeTicker.java:10) ~[wakes-0.1.7.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:63) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-5dc3b66c74aa05fa.jar:?]
	at net.minecraft.class_638.handler$zjg000$fabric-lifecycle-events-v1$tickWorldAfterBlockEntities(class_638.java:2125) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18116(class_638.java:260) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1901) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.14.21-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
```
If the issue persists I'll try the Voyager fix. Really hope you can figure this one out though, Wakes is a fantastic mod.

**Comment by uricot** [comment]
Voyager is old and crashes my game

**Comment by Goby56** [comment]
It seems as though the last version introduced another problem. Instead of crashing with a ConcurrentModificationException it produced an IndexOutOfBoundsException.

0.2.0 should be the final nail in the coffin to stop this. Please try it out.

**Comment by papamaionise** [comment]
> It seems as though the last version introduced another problem. Instead of crashing with a ConcurrentModificationException it produced an IndexOutOfBoundsException.
> 
> 0.2.0 should be the final nail in the coffin to stop this. Please try it out.

Don't know about them but it resolved my issue it's no longer crashing usually it crashes after 2-3 minutes but I tested for way longer and it didn't 

THANKS FOR MAKING THIS AMAZING MOD!!!

**Comment by Lafolie** [comment]
Can confirm better results with this update. Played for several hours and did not experience a crash. I also have a world that crashes on startup with the old version, I'll try that and report back.

**Comment by Lafolie** [comment]
> I also have a world that crashes on startup with the old version, I'll try that and report back.

Tested the new version on that world. Worked fine. Seems like the bug is quashed.
