### ISSUE TITLE
wakes don't appear but black planes do occasionally and the game crashes sometimes

### ISSUE THREAD

**Issue by papamaionise** [Goby56/wakes#103]
wakes don't appear but black planes do occasionally and the game crashes sometimes
this issue started happening after the 0.3.0 update  the 0.2.4 update of wakes mod works just fine and I'm using 1.20.1 fabric
[crash-2024-08-28_01.22.37-server.txt](https://github.com/user-attachments/files/16817317/crash-2024-08-28_01.22.37-server.txt)

**Comment by KhriszB** [comment]
I always crashing too. 
```
21:58:04] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1002) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:889) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:113) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:691) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_8316(net.minecraft.class_2338)" because "net.minecraft.class_310.method_1551().field_1687" is null
	at com.goby56.wakes.simulation.WakeNode.validPos(WakeNode.java:199) ~[wakes-0.3.0+1.20.5.jar:?]
	at com.goby56.wakes.simulation.WakeHandler.insert(WakeHandler.java:76) ~[wakes-0.3.0+1.20.5.jar:?]
	at com.goby56.wakes.utils.WakesUtils.placeWakeTrail(WakesUtils.java:95) ~[wakes-0.3.0+1.20.5.jar:?]
	at net.minecraft.class_1297.spawnEffects(class_1297.java:22505) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.handler$hdc014$wakes$tick(class_1297.java:22476) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.method_5773(class_1297.java:484) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2490) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_5773(class_1308.java:377) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:769) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:492) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:407) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:371) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:998) ~[client-intermediary.jar:?]
	... 5 more
[21:58:04] [Server thread/ERROR]: This crash report has been saved to: /Users/khriszb/Library/Application Support/PrismLauncher/instances/TryCraft/.minecraft/crash-reports/crash-2024-09-01_21.58.04-server.txt
[21:58:04] [Server thread/INFO]: Stopping server
```

**Comment by Katboi32** [comment]
This is also an issue for me

**Comment by Goby56** [comment]
Could you elaborate on the "appear black" part and show some screenshots?

**Comment by Goby56** [comment]
And when does this crash happen? Is it when immidiately launching the game, joining a world, or when in the water?

**Comment by Goby56** [comment]
Closing as the crash seems to be for the same reason as #102 . Please open a separate issue for the black planes or find an already open issue that closely resembles your issue with non-existent/black planes.
