### ISSUE TITLE
Crash during world save

### ISSUE THREAD

**Issue by ninjaguardian** [Goby56/wakes#106]
**Describe the bug**
When I save and quit, I crash.

**Expected behavior**
It should save the game without crashing.

**To Reproduce**
Probably just get the mods I use, and save your game.

**Hardware and OS**
Windows 11
Nvidia RTX 3060

**Versions**
- Minecraft version: 1.20.1
- Mod loader: Quilt
- Loader version: 0.26.4
- Wakes: 0.3.0
- YACL: 3.5.0+1.20.1-fabric (quilt version only goes up to 3.2.2+1.20 so I used the fabric one)
- QFAPI: 7.6.0+0.92.2

**Additional information**
[logs](https://mclo.gs/wBBRVRj)

**Comment by thimblebird** [comment]
i additionally can't delete worlds and can't enter old worlds, if this is related.

Minecraft version: 1.21.1
Java version: 21.0.3
Fabric loader version: 0.16.5

log: https://mclo.gs/pH8mkET

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-09-25 07:41:40
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_8316(net.minecraft.class_2338)" because "net.minecraft.class_310.method_1551().field_1687" is null
	at com.goby56.wakes.simulation.WakeNode.validPos(WakeNode.java:199)
	at com.goby56.wakes.simulation.WakeHandler.insert(WakeHandler.java:76)
	at com.goby56.wakes.utils.WakesUtils.placeWakeTrail(WakesUtils.java:95)
	at net.minecraft.entity.Entity.spawnEffects(Entity.java:11055)
	at net.minecraft.entity.Entity.handler$dmd005$wakes$tick(Entity.java:11026)
	at net.minecraft.entity.Entity.tick(Entity.java:488)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity.java:2468)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity.java:372)
	at net.minecraft.class_3218.mixinextras$bridge$method_5773$205(class_3218.java)
	at net.minecraft.server.world.ServerWorld.wrapOperation$dcm000$puzzleslib$tickNonPassenger(ServerWorld.java:8797)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld.java:770)
	at net.minecraft.world.World.tickEntity(World.java:498)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld.java:408)
	at net.minecraft.world.EntityList.forEach(EntityList.java:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:372)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:912)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.goby56.wakes.simulation.WakeNode.validPos(WakeNode.java:199)
	at com.goby56.wakes.simulation.WakeHandler.insert(WakeHandler.java:76)
	at com.goby56.wakes.utils.WakesUtils.placeWakeTrail(WakesUtils.java:95)
	at net.minecraft.entity.Entity.spawnEffects(Entity.java:11055)
	at net.minecraft.entity.Entity.handler$dmd005$wakes$tick(Entity.java:11026)
	at net.minecraft.entity.Entity.tick(Entity.java:488)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity.java:2468)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity.java:372)
	at net.minecraft.class_3218.mixinextras$bridge$method_5773$205(class_3218.java)
	at net.minecraft.server.world.ServerWorld.wrapOperation$dcm000$puzzleslib$tickNonPassenger(ServerWorld.java:8797)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld.java:770)
	at net.minecraft.world.World.tickEntity(World.java:498)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld.java:408)
	at net.minecraft.world.EntityList.forEach(EntityList.java:54)

-- Entity being ticked --
Details:
	Entity Type: minecraft:glow_squid (net.minecraft.class_5776)
	Entity ID: 15466
	Entity Name: Glow Squid
	Entity's Exact location: -1.32, -31.37, -7.00
	Entity's Block location: World: (-2,-32,-8), Section: (at 14,0,8 in -1,-2,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: -0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.World.tickEntity(World.java:498)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld.java:408)
	at net.minecraft.world.EntityList.forEach(EntityList.java:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:372)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:912)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Unknown Source)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 841
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,68,0), Section: (at 0,4,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 25643 game time, 52841 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Commands: true
	Level weather: Rain time: 39323 (now: false), thunder time: 131484 (now: false)
	Known server brands: vanilla, fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 94
Stacktrace:
	at net.minecraft.server.world.ServerWorld.addDetailsToCrashReport(ServerWorld.java:1693)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:1024)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:912)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 915922448 bytes (873 MiB) / 3363831808 bytes (3208 MiB) up to 17045651456 bytes (16256 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: Rocket Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2080 Ti
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 11264.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6109
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 34694.87
	Virtual memory used (MiB): 17005.77
	Swap memory total (MiB): 2048.00
	Swap memory used (MiB): 35.13
	Space in storage for jna.tmpdir (MiB): available: 161326.86, total: 476039.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 161326.86, total: 476039.00
	Space in storage for io.netty.native.workdir (MiB): available: 161326.86, total: 476039.00
	Space in storage for java.io.tmpdir (MiB): available: 161326.86, total: 476039.00
	Space in storage for workdir (MiB): available: 161326.86, total: 476039.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16256M -XX:+DisableExplicitGC -XX:+UseCompressedOops
	Fabric Mods: 
		axolotlbuckets: Axolotl Buckets 1.2.0
		carpetvariants: Carpet Variants 1.21.1-1.0.2
		clean-debug: Clean F3 0.4.7
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.84
		dynamic_asset_generator: Dynamic Asset Generator 6.1.2
		dynamiclights: Dynamic Lights 1.8.3+mod
		dynamicsoundfilters: Dynamic Sound Filters 1.4.0+1.21.1
		easyanvils: Easy Anvils 21.1.0
		easymagic: Easy Magic 21.1.0
		enhancedblockentities: Enhanced Block Entities 0.10.2+1.21
		entityculling: EntityCulling 1.7.0
		evs: Enchanted Vertical Slabs 2.3
		excavated_variants: Excavated Variants 4.3.1
			defaultresources: Default Resources 3.6.0
		fabric-api: Fabric API 0.104.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.22+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.7.0+4053855719
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.28+1daea21519
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.19+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92119
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.5+3fc0e55219
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df36019
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b19
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+5659912919
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.2.0+d38f898f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.5
		ferritecore: FerriteCore 7.0.0
		fog: Fog 1.4.1-1.21.1
			architectury: Architectury 13.0.6
		forgeconfigapiport: Forge Config API Port 21.1.0
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		head_in_the_clouds: Head In The Clouds 1.1.0
		hideexperimentalwarning: Hide Experimental Warning 1.2
		indium: Indium 1.0.35+mc1.21
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		kiwi: Kiwi Library 15.1.1+fabric
		letitrain: letitrain 2.2.2
		lithium: Lithium 0.13.1
		midnightlib: MidnightLib 1.6.3
		minecraft: Minecraft 1.21.1
		modernfix: ModernFix 5.19.3+mc1.21.1
		modmenu: Mod Menu 11.0.2
		mr_better_babies: Better Babies 0.7.13
		mr_developer_resources: Data API 1.6.3
		mr_true_ending: True Ending: Ender Dragon Overhaul 1-v1.1.2d
		mr_typewriter_daycounter: Typewriter Daycounter 1.0
		mru: Mineblock's Repeated Utilities 1.0.2+1.21+fabric
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		notenoughanimations: NotEnoughAnimations 1.7.6
		nullscape: Nullscape 1.2.7
		nvidium: Nvidium 0.3.1
		owo: oωo 0.12.14+1.21
			blue_endless_jankson: jankson 1.2.2
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		particlerain: Particle Rain 2.1.4
		particular: Particular 1.1.1+1.21
		placeholder-api: Placeholder API 2.4.1+1.21
		puzzleslib: Puzzles Lib 21.1.10
		shulkerboxtooltip: Shulker Box Tooltip 5.1.1+1.21.1
		slimyboyos: SlimyBoyos 14.0.2
		snowrealmagic: Snow! Real Magic! 11.0.7+fabric
		sodium: Sodium 0.5.11+mc1.21
		sounds: Sounds 2.1.0+1.21+fabric
			mixinextras: MixinExtras 0.5.0-beta.2
			yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
				com_twelvemonkeys_common_common-image: common-image 3.10.0
				com_twelvemonkeys_common_common-io: common-io 3.10.0
				com_twelvemonkeys_common_common-lang: common-lang 3.10.0
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
		swingthrough: SwingThrough 1.0.5+1.21
		threadtweak: ThreadTweak 0.1.5+mc1.21.1
		villagerhats: Villager Hats 1.7.2+1.21
		visuality: Visuality 0.7.7+1.21
		visualkeys: VisualKeys 0.0.3
		visualworkbench: Visual Workbench 21.1.0
		wakes: Wakes 0.3.0+1.21.1
			com_github_jdiemke_delaunay-triangulator_delaunaytriangulator: DelaunayTriangulator 1.0.0
			satin: Satin 2.0.0
	Loaded Shaderpack: RenderPearl v2.1.2.zip
		Profile: HIGH (+0 options changed by user)
	Server Running: true
	Player Count: 0 / 8; []
	Active Data Packs: vanilla, dynamic_asset_generator/dynamic_asset_generator:builtin_data, dynamic_asset_generator/excavated_variants:data, fabric, carpetvariants, collective, dynamiclights, easyanvils (incompatible), easymagic (incompatible), evs, excavated_variants, fabric-convention-tags-v2, fog (incompatible), mr_better_babies, mr_developer_resources, mr_true_ending, mr_typewriter_daycounter, nullscape, slimyboyos (incompatible), snowrealmagic (incompatible), sounds (incompatible), villagerhats (incompatible), visualworkbench (incompatible)
	Available Data Packs: bundle, carpetvariants, collective, dynamic_asset_generator/dynamic_asset_generator:builtin_data, dynamic_asset_generator/excavated_variants:data, dynamiclights, easyanvils (incompatible), easymagic (incompatible), evs, excavated_variants, fabric, fabric-convention-tags-v2, fog (incompatible), mr_better_babies, mr_developer_resources, mr_true_ending, mr_typewriter_daycounter, nullscape, slimyboyos (incompatible), snowrealmagic (incompatible), sounds (incompatible), trade_rebalance, vanilla, villagerhats (incompatible), visualworkbench (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	World Seed: -8203119802552239462
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.21.1

```

**Comment by theDerpu** [comment]
I'm getting the same issue, older version is too lagy and newer one doesn't let me play

**Comment by ninjaguardian** [comment]
> i additionally can't delete worlds after i was already in a world and can't enter other worlds after i was already in a world, if this is related.
> 
> Minecraft version: 1.21.1 Java version: 21.0.3 Fabric loader version: 0.16.5
> 
> log: https://mclo.gs/pH8mkET

Possibly due to puzzleslib

**Comment by ninjaguardian** [comment]
Duplicate of https://github.com/Goby56/wakes/issues/112
